- name: Add group gitea
  group:
    name: "{{ gitea_group }}"
    state: present
    system: yes

- name: Add user gitea
  user:
    name: "{{ gitea_user }}"
    state: present
    group: "{{ gitea_group }}"
    system: yes
    home: "{{ gitea_home }}"
    shell: "/bin/false"
